name: Lint and Test

on:
  push:
    branches:
      - master  # Adjust to the branch you're working with
  pull_request:
    branches:
      - master  # Runs on pull requests targeting the main branch

jobs:
  lint-and-test:
    runs-on: ubuntu-latest  # Use Ubuntu runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Node.js version 18.18.0 or above
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.18.0'  # Ensure Node.js version is 18.18.0 or higher

      # Set up the DATABASE_URL secret as an environment variable
      - name: Set environment variables
        run: echo "DATABASE_URL=postgresql://postgres:postgres@localhost:5432/testdb" >> $GITHUB_ENV

      # Check the Node version to make sure the correct one is installed
      - name: Check Node.js version
        run: node --version

      # Install dependencies
      - name: Install dependencies
        run: yarn install  # Use yarn to install dependencies

      # Run tests
      - name: Run tests
        run: yarn test
